### ISSUE TITLE
Preprocessing for GHG

### ISSUE THREAD

**Issue by kkaytekin** [humansensinglab/Generalizable-Human-Gaussians#2]
Hello,
Is there a script which we can use to obtain the items listed in lines 34-44 here? : https://github.com/humansensinglab/Generalizable-Human-Gaussians/blob/7bb6a68e6ffb94c7b5e6f6a95e4a414aa7c742b5/INSTALL.md?plain=1#L34-L44

Best regards,
Kagan

**Comment by YoungJoongUNC** [comment]
Hi Kagan, I will upload the script to render the position map, visibility map, and also the script to generate the transform within 3-5 days!

**Comment by sunshinnnn** [comment]
Hi Youngjoong, how's the data preprocessing script going? I also want to try it on custom data. :yum:

**Comment by YoungJoongUNC** [comment]
Hi, so sorry for the delay! Let me upload them in a few hours!

**Comment by YoungJoongUNC** [comment]
Just uploaded the rendering images / mask part! Working on the visibility map and position map rendering part now.

**Comment by YoungJoongUNC** [comment]
I just uploaded scripts for rendering visibility map and position map. Please refer to the [CUSTOM_DATASET.md](https://github.com/humansensinglab/Generalizable-Human-Gaussians/blob/main/CUSTOM_DATASET.md).
