### ISSUE TITLE
Question about paper

### ISSUE THREAD

**Issue by glorioushonor** [humansensinglab/Generalizable-Human-Gaussians#3]
Hello, may I ask what the meaning of "i=1...S" in Fig.2 is? Does it refer to the dimensions of the parameters "position" and "color"? I couldn’t find a corresponding explanation in the paper.

**Comment by phphuc612** [comment]
You can refer to section 3.3 for multi-scaffolds. The S represents the number of scaffolds for reconstruction.

**Comment by YoungJoongUNC** [comment]
Hello, it represents the index of the scaffold.
For example, S=0 denotes the base scaffold (i.e., the SMPL surface).
S=1 denotes the 1st outer scaffold, which is dilated by 1 cm from the SMPL surface.

Thank you @phphuc612 !
