### ISSUE TITLE
train code

### ISSUE THREAD

**Issue by hengyu-wang** [humansensinglab/Generalizable-Human-Gaussians#6]
Thank you for your excellent work. Will you be releasing the code for training the model?

**Comment by YoungJoongUNC** [comment]
Hi Hengyu, 

I am sorry for the delayed reply! I am currently very busy, so not very sure when I can finish cleaning the script. If it is urgent, could you please leave your email here, and I can send you the raw version.

Meanwhile, you could use this information to implement the training script.

For the training, I used the exactly same dataloader that can be found here (def get_item): https://github.com/humansensinglab/Generalizable-Human-Gaussians/blob/main/lib/ghg/human_loader.py#L160

Specifically, during the data loading process for the training, I first choose three novel views, and then choose three input views.

(1) When selecting the novel views, I randomly choose three uniformly distributed angles (I employ multi-view supervision therefore we have “three” novel views).

To be specific, from the subject_id, we get the first novel view angle”  : https://github.com/humansensinglab/Generalizable-Human-Gaussians/blob/main/lib/ghg/human_loader.py#L196
Then the remaining two novel view angles are chosen in a way that the three total angles are uniformly distributed.

(2)For selecting the “subangle”, it is chosen randomly among the subangle “2,3,4” here: https://github.com/humansensinglab/Generalizable-Human-Gaussians/blob/main/lib/ghg/human_loader.py#L301

Hope this helps!

**Comment by hengyu-wang** [comment]
> Hi Hengyu,
> 
> I am sorry for the delayed reply! I am currently very busy, so not very sure when I can finish cleaning the script. If it is urgent, could you please leave your email here, and I can send you the raw version.
> 
> Meanwhile, you could use this information to implement the training script.
> 
> For the training, I used the exactly same dataloader that can be found here (def get_item): https://github.com/humansensinglab/Generalizable-Human-Gaussians/blob/main/lib/ghg/human_loader.py#L160
> 
> Specifically, during the data loading process for the training, I first choose three novel views, and then choose three input views.
> 
> (1) When selecting the novel views, I randomly choose three uniformly distributed angles (I employ multi-view supervision therefore we have “three” novel views).
> 
> To be specific, from the subject_id, we get the first novel view angle” : https://github.com/humansensinglab/Generalizable-Human-Gaussians/blob/main/lib/ghg/human_loader.py#L196 Then the remaining two novel view angles are chosen in a way that the three total angles are uniformly distributed.
> 
> (2)For selecting the “subangle”, it is chosen randomly among the subangle “2,3,4” here: https://github.com/humansensinglab/Generalizable-Human-Gaussians/blob/main/lib/ghg/human_loader.py#L301
> 
> Hope this helps!

Thank you for your response. I would be very grateful if you could provide me with the original version of the code. My email is [why3065619030@163.com](mailto:why3065619030@163.com).

**Comment by YoungJoongUNC** [comment]
Hi Hengyu,

I just uploaded the [nightly version of training script](https://github.com/humansensinglab/Generalizable-Human-Gaussians/blob/main/train_nightly_ver.py), which can be run by : python train_nightly_ver.py

I have not tested it yet, so it might have bug. Also please note that I have added some modifications to the script so the training result might have some performance difference. 

To enhance the performance, feel free to try different approaches for the appearance map aggregation [here](https://github.com/humansensinglab/Generalizable-Human-Gaussians/blob/main/lib/ghg/network_train_nightly_ver.py#L207). For example, using the weighted averaging of the pixels during training, instead of choosing the pixel that has the best visibility, leads to better performance.

Hope this helps!

**Comment by hengyu-wang** [comment]
thank you！


---- Replied Message ----
| From | Youngjoong ***@***.***> |
| Date | 11/09/2024 14:00 |
| To | humansensinglab/Generalizable-Human-Gaussians ***@***.***> |
| Cc | hongyu ***@***.***>,
Author ***@***.***> |
| Subject | Re: [humansensinglab/Generalizable-Human-Gaussians] train code (Issue #6) |

Hi Hengyu,

I just uploaded the nightly version of training script, which can be run by : python train_nightly_ver.py

I have not tested it yet, so it might have bug. Also please note that I have added some modifications to the script so the training result might have some performance difference.

To enhance the performance, feel free to try different approaches for the appearance map aggregation here. For example, using the weighted averaging of the pixels during training, instead of choosing the pixel that has the best visibility, leads to better performance.

Hope this helps!
