### ISSUE TITLE
About SMPL-X parameters at test time

### ISSUE THREAD

**Issue by DecAd3** [humansensinglab/Generalizable-Human-Gaussians#7]
Hi authors, thank you for your great work!

I would like to know which off-the-shelf methods were used to estiamte SMPL-X parameters in your experiments? Did you use the estimation results directly or were there any refinement steps to make them better?

Thanks in advance!

**Comment by YoungJoongUNC** [comment]
We used the official SMPL-X parameters provided by the THuman authors. 
However, when we render the THuman 3D scans, we scale both the 3D scans and SMPL-X [here](https://github.com/humansensinglab/Generalizable-Human-Gaussians/blob/main/process_dataset/render_image.py#L147).

If you are asking about a general method to estimate SMPL-X parameters, you can use [EasyMocap](https://github.com/zju3dv/EasyMocap).
